# One-Hot Encoding

In [1]:
sentence = "AI loves Python"
words = sentence.split()
vocabulary = sorted(set(words))
print(vocabulary)

['AI', 'Python', 'loves']


In [2]:
wrod_to_index = {word: index for index, word in enumerate(vocabulary)}
print(wrod_to_index)

{'AI': 0, 'Python': 1, 'loves': 2}


In [3]:
import numpy as np
for word in vocabulary:
    one_hot_vector = np.zeros(len(vocabulary))
    one_hot_vector[wrod_to_index[word]] = 1
    print(f"One-hot vector for '{word}': {one_hot_vector}")

One-hot vector for 'AI': [1. 0. 0.]
One-hot vector for 'Python': [0. 1. 0.]
One-hot vector for 'loves': [0. 0. 1.]


In [5]:
endoded_sentence= []
for word in words:
    one_hot_vector = np.zeros(len(vocabulary))
    one_hot_vector[wrod_to_index[word]] = 1
    endoded_sentence.append(one_hot_vector)
print("Encoded sentence:\n", endoded_sentence)

Encoded sentence:
 [array([1., 0., 0.]), array([0., 0., 1.]), array([0., 1., 0.])]


In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np
encoder = OneHotEncoder(sparse_output=False)
data = np.array(words).reshape(-1, 1)
encoded_data = encoder.fit_transform(data)
print("Encoded data using OneHotEncoder:\n", encoded_data)

Encoded data using OneHotEncoder:
 [[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


# Lecture 61 – Bag of Words (BoW) + N-Grams

In [8]:
documents= [
    "I love programming in Python.",
    "Natural Language Processing is fascinating.",
    "AI is transforming the world.",    
]
print(documents)

['I love programming in Python.', 'Natural Language Processing is fascinating.', 'AI is transforming the world.']


In [9]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

print(X.toarray())

[[0 0 1 0 0 1 0 0 1 1 0 0 0]
 [0 1 0 1 1 0 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 1 1 1]]


In [10]:
print("Feature names:", vectorizer.get_feature_names_out())

Feature names: ['ai' 'fascinating' 'in' 'is' 'language' 'love' 'natural' 'processing'
 'programming' 'python' 'the' 'transforming' 'world']


In [11]:
bigram_vectorizer = CountVectorizer(ngram_range=(2, 2))
X_bigrams = bigram_vectorizer.fit_transform(documents)
print("Bigram feature names:", bigram_vectorizer.get_feature_names_out())

Bigram feature names: ['ai is' 'in python' 'is fascinating' 'is transforming'
 'language processing' 'love programming' 'natural language'
 'processing is' 'programming in' 'the world' 'transforming the']


In [12]:
print(X_bigrams.toarray())

[[0 1 0 0 0 1 0 0 1 0 0]
 [0 0 1 0 1 0 1 1 0 0 0]
 [1 0 0 1 0 0 0 0 0 1 1]]


In [13]:
combined = CountVectorizer(ngram_range=(1, 2))
X_combined = combined.fit_transform(documents)
print("Combined feature names:", combined.get_feature_names_out())
print(X_combined.toarray())

Combined feature names: ['ai' 'ai is' 'fascinating' 'in' 'in python' 'is' 'is fascinating'
 'is transforming' 'language' 'language processing' 'love'
 'love programming' 'natural' 'natural language' 'processing'
 'processing is' 'programming' 'programming in' 'python' 'the' 'the world'
 'transforming' 'transforming the' 'world']
[[0 0 0 1 1 0 0 0 0 0 1 1 0 0 0 0 1 1 1 0 0 0 0 0]
 [0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]]


In [14]:
# tf-idf   
docuements = [
    "I love programming in Python.",  
    "Natural Language Processing is fascinating.",
    "AI is transforming the world.",
]

from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X_tfidf = vectorizer.fit_transform(documents)

In [15]:
X= vectorizer.fit_transform(documents)
print("X.toarray():\n", X.toarray())

X.toarray():
 [[0.         0.         0.5        0.         0.         0.5
  0.         0.         0.5        0.5        0.         0.
  0.        ]
 [0.         0.46735098 0.         0.35543247 0.46735098 0.
  0.46735098 0.46735098 0.         0.         0.         0.
  0.        ]
 [0.46735098 0.         0.         0.35543247 0.         0.
  0.         0.         0.         0.         0.46735098 0.46735098
  0.46735098]]


In [16]:
print("Feature names:", vectorizer.get_feature_names_out())

Feature names: ['ai' 'fascinating' 'in' 'is' 'language' 'love' 'natural' 'processing'
 'programming' 'python' 'the' 'transforming' 'world']


In [17]:
import pandas as pd
df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
print(df)

         ai  fascinating   in  ...       the  transforming     world
0  0.000000     0.000000  0.5  ...  0.000000      0.000000  0.000000
1  0.000000     0.467351  0.0  ...  0.000000      0.000000  0.000000
2  0.467351     0.000000  0.0  ...  0.467351      0.467351  0.467351

[3 rows x 13 columns]


In [18]:
from sklearn.feature_extraction.text import CountVectorizer
count_vectorizer = CountVectorizer()
X_count = count_vectorizer.fit_transform(documents)
X_df = pd.DataFrame(X_count.toarray(), columns=count_vectorizer.get_feature_names_out())
print("Count Vectorizer DataFrame:\n", X_df)

Count Vectorizer DataFrame:
    ai  fascinating  in  is  ...  python  the  transforming  world
0   0            0   1   0  ...       1    0             0      0
1   0            1   0   1  ...       0    0             0      0
2   1            0   0   1  ...       0    1             1      1

[3 rows x 13 columns]


In [19]:
vectorizer = TfidfVectorizer(stop_words='english')
X= vectorizer.fit_transform(documents)
pdf = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
print("TF-IDF DataFrame with stop words removed:\n", pdf)

TF-IDF DataFrame with stop words removed:
         ai  fascinating  language  ...   python  transforming    world
0  0.00000          0.0       0.0  ...  0.57735       0.00000  0.00000
1  0.00000          0.5       0.5  ...  0.00000       0.00000  0.00000
2  0.57735          0.0       0.0  ...  0.00000       0.57735  0.57735

[3 rows x 10 columns]


# Lecture 63 – Word Embeddings & Word2Vec Intuition

In [20]:
pip install gensim

   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   --- ------------------------------------ 2.4/24.4 MB 11.8 MB/s eta 0:00:02
   -------- ------------------------------- 5.0/24.4 MB 11.9 MB/s eta 0:00:02
   ------------ --------------------------- 7.3/24.4 MB 11.5 MB/s eta 0:00:02
   ---------------- ----------------------- 10.0/24.4 MB 11.6 MB/s eta 0:00:02
   -------------------- ------------------- 12.3/24.4 MB 11.5 MB/s eta 0:00:02
   ---------------------- ----------------- 13.9/24.4 MB 10.7 MB/s eta 0:00:01
   ------------------------ --------------- 14.9/24.4 MB 10.1 MB/s eta 0:00:01
   ------------------------- -------------- 15.7/24.4 MB 9.3 MB/s eta 0:00:01
   --------------------------- ------------ 16.8/24.4 MB 8.8 MB/s eta 0:00:01
   ----------------------------- ---------- 17.8/24.4 MB 8.5 MB/s eta 0:00:01
   -------------------------------- ------- 19.7/24.4 MB 8.5 MB/s eta 0:00:01
   ---------------------------------- ----- 21.2/24.4 MB 8.5 MB/s et

In [1]:
sentences = [
    ["i", "love", "machine", "learning"],
    ["artificial", "intelligence", "is", "powerful"],
    ["python", "is", "great"],
    ["machine", "learning", "uses", "python"]
]

In [2]:
from gensim.models import Word2Vec

model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)


In [3]:
vector = model.wv['machine']
print("Vector representation for 'machine':\n", vector)

Vector representation for 'machine':
 [-8.2426779e-03  9.2993546e-03 -1.9766092e-04 -1.9672764e-03
  4.6036304e-03 -4.0953159e-03  2.7431143e-03  6.9399667e-03
  6.0654259e-03 -7.5107943e-03  9.3823504e-03  4.6718083e-03
  3.9661205e-03 -6.2435055e-03  8.4599797e-03 -2.1501649e-03
  8.8251876e-03 -5.3620026e-03 -8.1294188e-03  6.8245591e-03
  1.6711927e-03 -2.1985089e-03  9.5136007e-03  9.4938548e-03
 -9.7740470e-03  2.5052286e-03  6.1566923e-03  3.8724565e-03
  2.0227872e-03  4.3050171e-04  6.7363144e-04 -3.8206363e-03
 -7.1402504e-03 -2.0888723e-03  3.9238976e-03  8.8186832e-03
  9.2591504e-03 -5.9759365e-03 -9.4026709e-03  9.7643770e-03
  3.4297847e-03  5.1661171e-03  6.2823449e-03 -2.8042626e-03
  7.3227035e-03  2.8302716e-03  2.8710044e-03 -2.3803699e-03
 -3.1282497e-03 -2.3701417e-03  4.2764368e-03  7.6057913e-05
 -9.5842788e-03 -9.6655441e-03 -6.1481940e-03 -1.2856961e-04
  1.9974159e-03  9.4319675e-03  5.5843508e-03 -4.2906962e-03
  2.7831673e-04  4.9643586e-03  7.6983096e-03 -

In [4]:
model.wv.most_similar('python', topn=3)

[('love', 0.21617142856121063),
 ('intelligence', 0.09291724115610123),
 ('i', 0.06285078078508377)]

In [5]:
similarity = model.wv.similarity('machine', 'learning')
print("Similarity between 'machine' and 'learning':", similarity)

Similarity between 'machine' and 'learning': -0.0135149285


# Lecture 64 – CBOW & Skip-Gram (Word2Vec Training Architectures)

In [6]:
from gensim.models import Word2Vec

In [7]:
sentences = [
    ["the", "cat", "drinks", "milk"],
    ["the", "dog", "drinks", "water"],
    ["artificial", "intelligence", "is", "powerful"],
    ["machine", "learning", "uses", "data"]
]

In [8]:
cbow_model = Word2Vec(sentences, vector_size=50, window=2, min_count=1, workers=4, sg=0,epochs=100)   #sg=0 shows Cbow

In [9]:
skipgram_model = Word2Vec(sentences, vector_size=50, window=2, min_count=1, workers=4, sg=1,epochs=100)   #sg=1 shows Skip-gram

In [10]:
print("CBOW:")
print(cbow_model.wv.most_similar("drinks"))

print("\nSkip-Gram:")
print(skipgram_model.wv.most_similar("drinks"))

CBOW:
[('dog', 0.16945351660251617), ('cat', 0.1537223607301712), ('is', 0.13586893677711487), ('data', 0.12754163146018982), ('artificial', 0.10086522251367569), ('the', 0.04469849169254303), ('milk', 0.042373571544885635), ('machine', 0.014789306558668613), ('water', -0.010323725640773773), ('uses', -0.015298263169825077)]

Skip-Gram:
[('dog', 0.16902482509613037), ('cat', 0.15244869887828827), ('is', 0.13656286895275116), ('data', 0.1273575723171234), ('artificial', 0.10160069167613983), ('the', 0.04584447667002678), ('milk', 0.04241090267896652), ('machine', 0.015137939713895321), ('water', -0.010650776326656342), ('uses', -0.01506955735385418)]


In [11]:
print(cbow_model.wv["cat"].shape)

print(skipgram_model.wv["cat"].shape)

(50,)
(50,)


# Lecture 65 – Average Word2Vec (Sentence Embeddings)

In [18]:
import numpy as np
from gensim.models import Word2Vec

In [19]:
sentences = [
    ["i", "love", "machine", "learning"],
    ["python", "is", "powerful"],
    ["artificial", "intelligence", "uses", "data"],
    ["machine", "learning", "is", "fun"]
]

In [20]:
model = Word2Vec(sentences, vector_size=50, window=2, min_count=1, workers=1,epochs=100)

In [21]:
print(model.wv["machine"])

[-0.01727132  0.00735241  0.01037568  0.01148439  0.01490959 -0.01237168
  0.00224943  0.01212533 -0.00571753 -0.01238253 -0.00078109 -0.01674598
 -0.01118212  0.01419399  0.00671348  0.01444646  0.01365377  0.01511733
 -0.00765349 -0.00115336  0.00472765 -0.00902429  0.01684356 -0.01968279
  0.01353714  0.00584345 -0.00985709  0.00885865 -0.0035169   0.0134144
  0.01993061 -0.00876393 -0.00117883 -0.01144313  0.00768925  0.00555363
  0.01384967  0.01219943  0.01906428  0.01855499  0.01579311 -0.01396279
 -0.01833896 -0.00073496 -0.00612141  0.01581174  0.01188636 -0.00310356
  0.00303907  0.00357815]


In [22]:
def average_word2vec(sentence, model):
    vectors = []

    for word in sentence:
        if word in model.wv:
            vectors.append(model.wv[word])

    if len(vectors) == 0:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [23]:
sentence = ["machine", "learning", "is", "fun"]

embedding = average_word2vec(sentence, model)

print(embedding)

[-4.7616959e-03 -5.4289773e-04  2.9690594e-03  9.5158843e-03
  2.8183241e-03 -4.7166222e-03  1.0583682e-02  7.4226344e-03
 -6.0852598e-03  3.5398952e-03 -1.5245378e-03 -3.1873046e-03
 -9.4263237e-03  4.3259049e-04  2.9614603e-04  6.6122282e-03
  8.3303368e-03  4.2065736e-03 -3.7660683e-03 -6.0660765e-04
  5.7406174e-03  8.7110791e-05  9.6266940e-03 -5.8411271e-03
  8.3528096e-03 -3.3018934e-03 -2.7698670e-03  3.5022462e-03
 -3.4188859e-03 -4.8298789e-03 -3.8995103e-03  6.5022381e-04
  9.6432380e-03 -6.2480811e-03 -1.5012174e-03  2.8274895e-04
  1.0611137e-02 -7.2502778e-03  4.5632138e-03  3.2711113e-03
  4.9099972e-04 -1.6647009e-03 -6.1519532e-03 -6.2341830e-03
  1.9683777e-03  7.6742461e-03 -2.6290584e-03 -6.9728959e-04
 -1.0406612e-03  1.0949896e-02]


In [24]:
print(embedding.shape)

(50,)


In [25]:
sentence1 = ["machine", "learning"]
sentence2 = ["artificial", "intelligence"]

emb1 = average_word2vec(sentence1, model)
emb2 = average_word2vec(sentence2, model)

from numpy.linalg import norm

cosine_similarity = np.dot(emb1, emb2) / (norm(emb1) * norm(emb2))

print(cosine_similarity)

-0.095656395


# Lecture 66 – Practical NLP Feature Engineering: Choosing the Right Representation

In [26]:
documents = [
    "I love machine learning",
    "Python is amazing",
    "Artificial intelligence is transforming the world"
]

print(documents)

['I love machine learning', 'Python is amazing', 'Artificial intelligence is transforming the world']


In [27]:
from sklearn.feature_extraction.text import CountVectorizer

bow = CountVectorizer()

X_bow = bow.fit_transform(documents)

print(X_bow.toarray())

[[0 0 0 0 1 1 1 0 0 0 0]
 [1 0 0 1 0 0 0 1 0 0 0]
 [0 1 1 1 0 0 0 0 1 1 1]]


In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(documents)

print(X_tfidf.toarray())

[[0.         0.         0.         0.         0.57735027 0.57735027
  0.57735027 0.         0.         0.         0.        ]
 [0.62276601 0.         0.         0.4736296  0.         0.
  0.         0.62276601 0.         0.         0.        ]
 [0.         0.42339448 0.42339448 0.32200242 0.         0.
  0.         0.         0.42339448 0.42339448 0.42339448]]


In [29]:
from gensim.models import Word2Vec

tokenized = [doc.lower().split() for doc in documents]

model = Word2Vec(
    tokenized,
    vector_size=50,
    window=2,
    min_count=1,
    workers=1,
    epochs=100
)

In [30]:
import numpy as np

def average_word2vec(sentence, model):
    vectors = [model.wv[word] for word in sentence if word in model.wv]

    if not vectors:
        return np.zeros(model.vector_size)

    return np.mean(vectors, axis=0)

In [31]:
embedding = average_word2vec(
    tokenized[0],
    model
)

print(embedding.shape)
print(embedding)

(50,)
[-0.00458158 -0.00030512  0.00486307 -0.0037639  -0.00835122 -0.00023437
  0.00294995 -0.00545392 -0.00934371 -0.00696216  0.00098313 -0.00225293
 -0.00187802 -0.00752918 -0.00366544 -0.00548359  0.00082537  0.00575879
 -0.00430143 -0.00348897 -0.00573804  0.00142862  0.01047627  0.01307189
 -0.00385851  0.00617722 -0.0038897   0.00406712  0.00034126  0.00072138
  0.00602272 -0.01049926  0.00253813 -0.01492892  0.00038144 -0.00690412
  0.00313058  0.0099187  -0.00344337 -0.00183658  0.0117853  -0.00496435
 -0.00997048 -0.00024707  0.00903374 -0.00650123  0.00372406  0.00189435
  0.00390322 -0.00621639]


# Lecture 67 – Introduction to Deep Learning for NLP

In [32]:
sentences = [
    "I deposited money in the bank.",
    "I sat on the river bank."
]

for sentence in sentences:
    print(sentence)

I deposited money in the bank.
I sat on the river bank.


In [33]:
for sentence in sentences:
    print(sentence.lower().split())

['i', 'deposited', 'money', 'in', 'the', 'bank.']
['i', 'sat', 'on', 'the', 'river', 'bank.']


In [34]:
pip install tensorflow

  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 2.1/351.2 MB 10.9 MB/s eta 0:00:33
    --------------------------------------- 4.7/351.2 MB 11.4 MB/s eta 0:00:31
    --------------------------------------- 7.1/351.2 MB 11.3 MB/s eta 0:00:31
   - -------------------------------------- 9.2/351.2 MB 11.2 MB/s eta 0:00:31
   - -------------------------------------- 11.5/351.2 MB 11.3 MB/s eta 0:00:30
   - -------------------------------------- 13.4/351.2 MB 11.0 MB/s eta 0:00:31
   - -------------------------------------- 14.7/351.2 MB 10.3 MB/s eta 0:00:33
   - -------------------------------------- 15.7/351.2 MB 9.7 MB/s eta 0:00:35
   - -------------------------------------- 17.0/351.2 MB 9.4 MB/s eta 0:00:36
   -- ------------------------------------- 18.4/351.2 MB 9.0 MB/s eta 0:00:37
   -- ------------------------------------- 19.4/351.2 MB 8

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.35.1 which is incompatible.


In [35]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

model = Sequential([
    Embedding(
        input_dim=1000,
        output_dim=16,
        input_length=10
    )
])

model.summary()

c:\Users\mohd saqib\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [36]:
sentence = ["I", "love", "deep", "learning"]

for index, word in enumerate(sentence):
    print(index, word)

0 I
1 love
2 deep
3 learning


# Lecture 68 – ANN vs RNN + RNN Forward Propagation

In [37]:
sentence = ["I", "love", "deep", "learning"]

for word in sentence:
    print(word)

I
love
deep
learning


In [38]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential([
    SimpleRNN(
        units=32,  #  32 hidden units
        input_shape=(5, 10)
    )
])

model.summary()

c:\Users\mohd saqib\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,376 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,376 (5.38 KB)

 Trainable params: 1,376 (5.38 KB)

 Non-trainable params: 0 (0.00 B)

In [39]:
import numpy as np
X= np.random.rand(2,5,10)  # 2 samples, 5 time steps, 10 features
print(X.shape)

(2, 5, 10)


In [40]:
# forward pass
output = model.predict(X)
print("Output shape:", output.shape)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 647ms/step
Output shape: (2, 32)


In [43]:
# return sequences 
model = Sequential([
    SimpleRNN(
        units=32,
        return_sequences=True,
        input_shape=(5, 10)
    )
])
model.summary()

c:\Users\mohd saqib\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 5, 32)          │         1,376 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,376 (5.38 KB)

 Trainable params: 1,376 (5.38 KB)

 Non-trainable params: 0 (0.00 B)

In [60]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

In [45]:
model = Sequential([
    SimpleRNN(
        16,
        input_shape=(5, 10)
    ),
    Dense(1)
])

model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_2 (SimpleRNN)        │ (None, 16)             │           432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 449 (1.75 KB)

 Trainable params: 449 (1.75 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
model.compile(optimizer='adam', loss='mse')

In [47]:
import numpy as np

X = np.random.rand(100, 5, 10)
y = np.random.rand(100, 1)

In [48]:
history = model.fit(
    X,
    y,
    epochs=5,
    verbose=1
)

Epoch 1/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - loss: 0.7252
Epoch 2/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.3957
Epoch 3/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.2304
Epoch 4/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.1890
Epoch 5/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.2040


In [49]:
print(history.history["loss"])

[0.7252089977264404, 0.3957279622554779, 0.23043861985206604, 0.18901000916957855, 0.20401185750961304]


# Lecture 70 – Limitations of RNNs + Simple RNN with Embeddings

In [61]:
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import SimpleRNN
from tensorflow.keras.layers import Dense

In [62]:
sentences = [
    "I love AI",
    "Python is amazing",
    "Deep learning is powerful"
]

In [63]:
from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

print(tokenizer.word_index)

{'is': 1, 'i': 2, 'love': 3, 'ai': 4, 'python': 5, 'amazing': 6, 'deep': 7, 'learning': 8, 'powerful': 9}


In [64]:
dequences = tokenizer.texts_to_sequences(sentences)
print(dequences)

[[2, 3, 4], [5, 1, 6], [7, 8, 1, 9]]


In [65]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

X = pad_sequences(
    dequences,
    maxlen=6
)

print(X)

[[0 0 0 2 3 4]
 [0 0 0 5 1 6]
 [0 0 7 8 1 9]]


In [66]:
model = Sequential([
    Embedding(
        input_dim=100,
        output_dim=16,
        input_length=6
    ),

    SimpleRNN(32),

    Dense(1, activation="sigmoid")
])

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [67]:
import numpy as np

y = np.array([1, 1, 1])

In [70]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [71]:
model.fit(
    X,
    y,
    epochs=5
)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.3333 - loss: 0.6987
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 1.0000 - loss: 0.6633
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 1.0000 - loss: 0.6286
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 149ms/step - accuracy: 1.0000 - loss: 0.5943
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - accuracy: 1.0000 - loss: 0.5603


# Lecture 71 – LSTM (Long Short-Term Memory): Intuition + Complete Architecture

In [ ]:
# short term memory refers to information needed right now.


# long-term memory refers to information that is stored for a longer period of time and can be retrieved later. In the context of neural networks, short-term memory is often associated with the hidden states of recurrent neural networks (RNNs), while long-term memory is associated with the weights and biases of the network that are learned during training.

In [72]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [73]:
sentences = [
    "I love deep learning",
    "Python is amazing",
    "Artificial intelligence is powerful"
]

In [74]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)

X = pad_sequences(sequences, maxlen=6)

print(X)

[[ 0  0  2  3  4  5]
 [ 0  0  0  6  1  7]
 [ 0  0  8  9  1 10]]


In [75]:
model = Sequential([
    Embedding(
        input_dim=100,
        output_dim=16,
        input_length=6
    ),

    LSTM(32),

    Dense(1, activation="sigmoid")
])

model.summary()

c:\Users\mohd saqib\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [76]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [77]:
import numpy as np

y = np.array([1, 1, 1])

In [78]:
model.fit(
    X,
    y,
    epochs=5
)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 0.0000e+00 - loss: 0.6972
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - accuracy: 0.3333 - loss: 0.6925
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step - accuracy: 1.0000 - loss: 0.6878
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.6831
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - accuracy: 1.0000 - loss: 0.6784


# Lecture 72   -  Gated Recurrent Unit


In [79]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import GRU
from tensorflow.keras.layers import Dense

In [80]:
sentences = [
    "Deep learning is amazing",
    "I enjoy studying AI",
    "Natural language processing is fun"
]

In [81]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)

X = pad_sequences(sequences, maxlen=6)

print(X)

[[ 0  0  2  3  1  4]
 [ 0  0  5  6  7  8]
 [ 0  9 10 11  1 12]]


In [82]:
model = Sequential([
    Embedding(
        input_dim=100,
        output_dim=16,
        input_length=6
    ),

    GRU(32),

    Dense(1, activation="sigmoid")
])

model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru (GRU)                       │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [83]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [84]:
import numpy as np

y = np.array([1, 1, 1])

In [85]:
model.fit(
    X,
    y,
    epochs=5
)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - accuracy: 1.0000 - loss: 0.6834
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 182ms/step - accuracy: 1.0000 - loss: 0.6751
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 1.0000 - loss: 0.6667
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - accuracy: 1.0000 - loss: 0.6582
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 1.0000 - loss: 0.6495


In [86]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [87]:
sentences = [
    "I love deep learning",
    "Natural language processing is interesting",
    "Artificial intelligence is transforming industries"
]

In [88]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer()

tokenizer.fit_on_texts(sentences)

sequences = tokenizer.texts_to_sequences(sentences)

X = pad_sequences(sequences, maxlen=8)

print(X)

[[ 0  0  0  0  2  3  4  5]
 [ 0  0  0  6  7  8  1  9]
 [ 0  0  0 10 11  1 12 13]]


In [89]:
model = Sequential([
    Embedding(
        input_dim=100,
        output_dim=16,
        input_length=8
    ),

    Bidirectional(
        LSTM(32)
    ),

    Dense(1, activation="sigmoid")
])

model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional (Bidirectional)   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [90]:
model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [91]:
import numpy as np
y = np.array([1, 1, 1])

In [92]:
model.fit(
    X,
    y,
    epochs=5
)

Epoch 1/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 1.0000 - loss: 0.6876
Epoch 2/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 1.0000 - loss: 0.6803
Epoch 3/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 1.0000 - loss: 0.6729
Epoch 4/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 1.0000 - loss: 0.6652
Epoch 5/5
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 1.0000 - loss: 0.6572


# Lecture 74 – Sequence-to-Sequence (Seq2Seq) Architecture + Introduction to Attention

In [93]:
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [94]:
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import LSTM

encoder_inputs = Input(shape=(None, 100))

encoder = LSTM(
    64,
    return_state=True
)

encoder_outputs, state_h, state_c = encoder(encoder_inputs)

print(state_h.shape)

(None, 64)


In [95]:
decoder_inputs = Input(shape=(None, 100))

decoder = LSTM(
    64,
    return_sequences=True,
    return_state=True
)

decoder_outputs, _, _ = decoder(
    decoder_inputs,
    initial_state=[state_h, state_c]
)

In [96]:
print("""
Input Sentence
      ↓
Encoder
      ↓
Context Vector
      ↓
Decoder
      ↓
Output Sentence
""")


Input Sentence
      ↓
Encoder
      ↓
Context Vector
      ↓
Decoder
      ↓
Output Sentence



In [97]:
words = ["I", "Love", "Machine", "Learning"]

attention_scores = [0.05, 0.70, 0.15, 0.10]

for word, score in zip(words, attention_scores):
    print(f"{word}: {score}")

I: 0.05
Love: 0.7
Machine: 0.15
Learning: 0.1


In [98]:
max_index = attention_scores.index(max(attention_scores))

print("Most important word:", words[max_index])

Most important word: Love


In [99]:
output_words = ["J'aime", "l'apprentissage", "automatique"]

attention = {
    "J'aime": "Love",
    "l'apprentissage": "Learning",
    "automatique": "Machine"
}

for out_word, in_word in attention.items():
    print(f"{out_word}  <-- focuses on -->  {in_word}")

J'aime  <-- focuses on -->  Love
l'apprentissage  <-- focuses on -->  Learning
automatique  <-- focuses on -->  Machine


# Lecture 75 – Why Transformers Changed AI

In [1]:
timeline = [
    "RNN",
    "LSTM",
    "GRU",
    "Seq2Seq",
    "Attention",
    "Transformer",
    "GPT",
    "Large Language Models"
]

for item in timeline:
    print(item)

RNN
LSTM
GRU
Seq2Seq
Attention
Transformer
GPT
Large Language Models


In [2]:
rnn = ["Word1", "Word2", "Word3", "Word4"]

print("Sequential Processing:")
for word in rnn:
    print(word)

Sequential Processing:
Word1
Word2
Word3
Word4


In [3]:
words = ["Word1", "Word2", "Word3", "Word4"]

print("Transformer processes all tokens together during training:")
print(words)

Transformer processes all tokens together during training:
['Word1', 'Word2', 'Word3', 'Word4']


In [4]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [5]:
from tensorflow.keras.preprocessing.text import Tokenizer

sentences = [
    "I love transformers",
    "Artificial intelligence is amazing"
]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)

print(tokenizer.word_index)

{'i': 1, 'love': 2, 'transformers': 3, 'artificial': 4, 'intelligence': 5, 'is': 6, 'amazing': 7}


In [6]:
sequences = tokenizer.texts_to_sequences(sentences)

print(sequences)

[[1, 2, 3], [4, 5, 6, 7]]


In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

model = Sequential([
    Embedding(
        input_dim=100,
        output_dim=8,
        input_length=6
    )
])

model.summary()

c:\Users\mohd saqib\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
# postiional encoding
sentence = "I love transformers"
for position, word in enumerate(sentence.split()):
    print(f"Word: {word}, Position: {position}")

Word: I, Position: 0
Word: love, Position: 1
Word: transformers, Position: 2


In [9]:
print("""
Sentence
   ↓
Tokenizer
   ↓
Token IDs
   ↓
Embeddings
   ↓
Positional Encoding
   ↓
Encoder
""")


Sentence
   ↓
Tokenizer
   ↓
Token IDs
   ↓
Embeddings
   ↓
Positional Encoding
   ↓
Encoder



In [10]:
sentence = [
    "The",
    "animal",
    "didn't",
    "cross",
    "the",
    "street",
    "because",
    "it",
    "was",
    "tired"
]

for word in sentence:
    print(word)

The
animal
didn't
cross
the
street
because
it
was
tired


In [11]:
words = ["animal", "street", "it"]

scores = {
    "animal": 0.82,
    "street": 0.10,
    "it": 0.08
}

for word, score in scores.items():
    print(f"{word}: {score}")

animal: 0.82
street: 0.1
it: 0.08


In [12]:
import tensorflow as tf

scores = tf.constant([2.0, 5.0, 1.0])

print(tf.nn.softmax(scores).numpy())

[0.04661262 0.93623954 0.01714782]


In [13]:
heads = [
    "Grammar Head",
    "Meaning Head",
    "Entity Head",
    "Context Head"
]

for head in heads:
    print(head)

Grammar Head
Meaning Head
Entity Head
Context Head


In [14]:
print("""
Input
  ↓
Q K V
  ↓
Attention Scores
  ↓
Softmax
  ↓
Weighted Sum
  ↓
Multi-Head
  ↓
Output
""")


Input
  ↓
Q K V
  ↓
Attention Scores
  ↓
Softmax
  ↓
Weighted Sum
  ↓
Multi-Head
  ↓
Output



## Lecture 78 – Feed Forward Network + Layer Normalization + Residual Connections

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

ffn = Sequential([
    Dense(64, activation="relu"),
    Dense(32)
])

ffn.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
import tensorflow as tf

x = tf.constant([1.0, 2.0, 3.0])

layer_output = tf.constant([0.2, 0.5, 0.7])

residual = x + layer_output

print(residual)

tf.Tensor([1.2 2.5 3.7], shape=(3,), dtype=float32)


In [ ]:
from tensorflow.keras.layers import LayerNormalization

layer_norm = LayerNormalization()

normalized = layer_norm([[1.0, 5.0, 10.0]])



print(normalized.numpy())

In [20]:
print("""
Embedding
      ↓
Positional Encoding
      ↓
Multi-Head Attention
      ↓
Add & Norm
      ↓
Feed Forward
      ↓
Add & Norm
      ↓
Encoder Output
""")


Embedding
      ↓
Positional Encoding
      ↓
Multi-Head Attention
      ↓
Add & Norm
      ↓
Feed Forward
      ↓
Add & Norm
      ↓
Encoder Output



In [21]:
sentence = ["I"]

print("Current Sequence:", sentence)

sentence.append("love")

print("Updated Sequence:", sentence)

Current Sequence: ['I']
Updated Sequence: ['I', 'love']


In [22]:
import numpy as np

mask = np.tril(np.ones((4, 4)))

print(mask)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [23]:
print("""
Previous Tokens
       ↓
Masked Attention
       ↓
Cross Attention
       ↓
Feed Forward
       ↓
Prediction
""")


Previous Tokens
       ↓
Masked Attention
       ↓
Cross Attention
       ↓
Feed Forward
       ↓
Prediction



# Lecture 80 – AI vs ML vs DL vs Generative AI

# Lecture 81 – What is a Large Language Model (LLM)?

# Lecture 93 – Hugging Face Pipelines & Text Generation

In [2]:
# from transformers import pipeline
# generator= pipeline("text-generation")
# generator("Artificial intelligence is")

[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
[transformers] No model was supplied, defaulted to HuggingFaceTB/SmolLM3-3B and revision a07cc9a.
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/1.92k [00:00<?, ?B/s]

c:\Users\mohd saqib\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\mohd saqib\.cache\huggingface\hub\models--HuggingFaceTB--SmolLM3-3B. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


NameError: name 'torch' is not defined

In [2]:
!pip install transformers
!pip install torch
!pip install accelerate

   ---------------------------------------- 0.0/122.1 MB ? eta -:--:--
    --------------------------------------- 2.1/122.1 MB 10.4 MB/s eta 0:00:12
   - -------------------------------------- 4.5/122.1 MB 10.7 MB/s eta 0:00:11
   -- ------------------------------------- 6.8/122.1 MB 11.0 MB/s eta 0:00:11
   --- ------------------------------------ 9.2/122.1 MB 11.1 MB/s eta 0:00:11
   --- ------------------------------------ 11.8/122.1 MB 11.3 MB/s eta 0:00:10
   ---- ----------------------------------- 13.6/122.1 MB 10.7 MB/s eta 0:00:11
   ---- ----------------------------------- 14.9/122.1 MB 10.2 MB/s eta 0:00:11
   ----- ---------------------------------- 16.3/122.1 MB 9.7 MB/s eta 0:00:11
   ----- ---------------------------------- 17.6/122.1 MB 9.3 MB/s eta 0:00:12
   ------ --------------------------------- 19.1/122.1 MB 8.9 MB/s eta 0:00:12
   ------ --------------------------------- 20.4/122.1 MB 8.7 MB/s eta 0:00:12
   ------- -------------------------------- 21.5/122.1 MB

In [3]:
from transformers import pipeline
classifier = pipeline("sentiment-analysis")
results = classifier("I love using transformers for NLP tasks!")
print(results)

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

c:\Users\mohd saqib\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\mohd saqib\.cache\huggingface\hub\models--distilbert--distilbert-base-uncased-finetuned-sst-2-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


model.safetensors: reconstructing file:   0%|          |  0.00B /  268MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

[{'label': 'POSITIVE', 'score': 0.9982925057411194}]


In [5]:
from transformers import pipeline

fill_mask = pipeline("fill-mask")

result=fill_mask("Paris is the <mask> of France.")
print(result)


[transformers] No model was supplied, defaulted to distilbert/distilroberta-base and revision fb53ab8.
Using a pipeline without specifying a model name and revision in production is not recommended.


Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

[transformers] RobertaForMaskedLM LOAD REPORT from: distilbert/distilroberta-base
Key                         | Status     |  | 
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  | 
roberta.pooler.dense.weight | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


[{'score': 0.6790177822113037, 'token': 812, 'token_str': ' capital', 'sequence': 'Paris is the capital of France.'}, {'score': 0.05177993327379227, 'token': 32357, 'token_str': ' birthplace', 'sequence': 'Paris is the birthplace of France.'}, {'score': 0.038252655416727066, 'token': 1144, 'token_str': ' heart', 'sequence': 'Paris is the heart of France.'}, {'score': 0.02434886246919632, 'token': 29778, 'token_str': ' envy', 'sequence': 'Paris is the envy of France.'}, {'score': 0.022851204499602318, 'token': 1867, 'token_str': ' Capital', 'sequence': 'Paris is the Capital of France.'}]


In [ ]:
from transformers import pipeline

qa = pipeline("question-answering")

context = """
Python is a programming language created by Guido van Rossum.
"""

question = "Who created Python?"

result = pipeline("question-answering")(question=question, context=context)

print(result)

In [4]:
from transformers import pipeline

generator = pipeline(
    "text-generation",
    model="gpt2"
)

result = generator(
    "Artificial Intelligence will",
    max_new_tokens=50
)

print(result[0]["generated_text"])

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

c:\Users\mohd saqib\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\mohd saqib\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


model.safetensors: reconstructing file:   0%|          |  0.00B /  548MB            

model.safetensors: downloading bytes:           |  0.00B            

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=50) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.


Artificial Intelligence will be the first such machine to be built in Russia.

"We are working on the technical feasibility of the system. We are looking at whether we can bring it to market and we are also looking at the technical feasibility of bringing it to market


In [5]:
temperature = 0.7
top_k = 50   
top_p = 0.9 

do_sample = True          
prompt = "Machine learing is"
generator(
"""
Write a LinkedIn post announcing
the completion of a Machine Learning course.
""",
max_new_tokens=120,
temperature=0.7
)



[transformers] Passing `generation_config` together with generation-related arguments=({'temperature', 'max_new_tokens'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Both `max_new_tokens` (=120) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)


[{'generated_text': '\nWrite a LinkedIn post announcing\nthe completion of a Machine Learning course.\n\nComplete the course online.\n\nContact your instructor or a mentor\n\nContact your mentor.\n\nRecruit or train an expert\n\nRecruit or train an expert.\n\nThe goal is to give an edge to the person or company who will be the next leader of a field. The more knowledge you acquire, the more effective you will be at making decisions. In this case, the expert should be a master in the technology sector or have a degree or other technical training in the industry.\n\nThe following is a list of the people to be considered for positions in this'}]

# Lecture 94 – NLP Pipelines: Classification, Summarization & Translation

In [6]:
from transformers import pipeline

classifier = pipeline("text-classification")

print(classifier("The lecture was excellent."))

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.


Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

[{'label': 'POSITIVE', 'score': 0.9998227953910828}]


In [ ]:
def summarizer(text, max_length=40, min_length=15, do_sample=False):
    prompt = f"Summarize this text:\n{text}\nSummary:"
    output = generator(
        prompt,
        max_new_tokens=max_length,
        do_sample=do_sample
    )
    summary_text = output[0]["generated_text"].split("Summary:")[-1].strip()
    return [{"summary_text": summary_text}]

text = """
Artificial Intelligence is transforming healthcare,
finance, education and many other industries.
"""

summary = summarizer(
    text,
    max_length=40,
    min_length=15,
    do_sample=False
)

print(summary)

KeyError: "Unknown task summarization, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [8]:
translator = pipeline(
    "translation",
    model="Helsinki-NLP/opus-mt-en-fr"
)

print(
    translator(
        "Artificial Intelligence is amazing."
    )
)

config.json:   0%|          | 0.00/1.42k [00:00<?, ?B/s]

c:\Users\mohd saqib\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\mohd saqib\.cache\huggingface\hub\models--Helsinki-NLP--opus-mt-en-fr. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


KeyError: "Unknown task translation, available tasks are ['any-to-any', 'audio-classification', 'automatic-speech-recognition', 'depth-estimation', 'document-question-answering', 'feature-extraction', 'fill-mask', 'image-classification', 'image-feature-extraction', 'image-segmentation', 'image-text-to-text', 'keypoint-matching', 'mask-generation', 'ner', 'object-detection', 'sentiment-analysis', 'table-question-answering', 'text-classification', 'text-generation', 'text-to-audio', 'text-to-speech', 'token-classification', 'video-classification', 'zero-shot-audio-classification', 'zero-shot-classification', 'zero-shot-image-classification', 'zero-shot-object-detection']"

In [ ]:
ner = pipeline(
    "ner",
    grouped_entities=True
)

text = """
Elon Musk visited India in 2025.
"""

print(ner(text))

[transformers] No model was supplied, defaulted to dbmdz/bert-large-cased-finetuned-conll03-english and revision 4c53496.
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

c:\Users\mohd saqib\anaconda3\Lib\site-packages\huggingface_hub\file_download.py:139: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\mohd saqib\.cache\huggingface\hub\models--dbmdz--bert-large-cased-finetuned-conll03-english. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


model.safetensors: reconstructing file:   0%|          |  0.00B / 1.33GB            

model.safetensors: downloading bytes:           |  0.00B            

In [ ]:
qa = pipeline("question-answering")

context = """
The Eiffel Tower is located in Paris.
"""

print(
    qa(
        question="Where is the Eiffel Tower located?",
        context=context
    )
)

In [ ]:
tasks = [
    "Classification",
    "Summarization",
    "Translation",
    "Named Entity Recognition",
    "Question Answering"
]

for task in tasks:
    print(task)

# Lecture 95 – Choosing the Right Hugging Face Model

# Lecture 96 – End-to-End Hugging Face Integration Project

In [ ]:
from transformers import pipeline

classifier = pipeline("text-classification")

summarizer = pipeline("summarization")

translator = pipeline(
    "translation",
    model="Helsinki-NLP/opus-mt-en-fr"
)

ner = pipeline(
    "ner",
    grouped_entities=True
)

qa = pipeline("question-answering")

In [ ]:
document = """
Microsoft announced a new AI platform during its annual conference.

The company plans to expand cloud services
while investing heavily in Generative AI.

Customers responded positively to the announcement.
"""

In [ ]:
sentiment = classifier(document)

print(sentiment)

In [ ]:
summary = summarizer(
    document,
    max_length=60,
    min_length=20,
    do_sample=False
)

print(summary)

In [ ]:
entities = ner(document)

print(entities)

In [ ]:
translated = translator(document)

print(translated)

In [ ]:
answer = qa(
    question="Which company announced the platform?",
    context=document
)

print(answer)

In [ ]:
report = {
    "Sentiment": sentiment,
    "Summary": summary,
    "Entities": entities,
    "Translation": translated,
    "Question Answer": answer
}

print(report)

In [ ]:
with open("report.md", "w") as file:
    file.write("# AI Analysis Report\n\n")
    file.write(str(report))

In [ ]:
# !pip install transformers gradio

In [ ]:
from transformers import pipeline
import gradio as gr

In [ ]:
classifier = pipeline("sentiment-analysis")

In [ ]:
def predict(text):
    return classifier(text)

In [ ]:
demo = gr.Interface(
    fn=predict,
    inputs="text",
    outputs="json",
    title="Sentiment Analyzer",
    description="Analyze the sentiment of any sentence."
)

demo.launch()

## Transformers task examples (for your current version)

In your installed `transformers` version, the generic `"translation"` task is not registered.
Use `"text2text-generation"` with translation models (or `"any-to-any"` when supported by the selected model).

The next cell gives:
1. A fixed English -> French translation example.
2. One demo example for each task listed in your error message.

Some tasks need extra libraries, large models, internet download, or specific input formats. The code uses `try/except` so one failure will not stop all examples.

In [ ]:
from pathlib import Path
import json
import math
import wave
import struct

from transformers import pipeline


# ---------- small local demo assets (image + short audio) ----------
assets_dir = Path("hf_demo_assets")
assets_dir.mkdir(exist_ok=True)

image_path = assets_dir / "demo_image.png"
audio_path = assets_dir / "demo_audio.wav"
video_path = assets_dir / "demo_video.mp4"  # placeholder path for video examples

# Create a tiny demo image if missing.
if not image_path.exists():
    try:
        from PIL import Image, ImageDraw

        img = Image.new("RGB", (320, 220), color=(245, 240, 230))
        draw = ImageDraw.Draw(img)
        draw.rectangle((35, 35, 285, 185), outline=(30, 30, 30), width=3)
        draw.text((90, 95), "Demo Image", fill=(20, 20, 20))
        img.save(image_path)
    except Exception as e:
        print("Could not create demo image:", e)

# Create a 1-second sine-wave audio file if missing.
if not audio_path.exists():
    sample_rate = 16000
    frequency = 440.0
    duration_sec = 1.0
    amplitude = 0.25

    with wave.open(str(audio_path), "w") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)  # int16
        wf.setframerate(sample_rate)

        total_frames = int(sample_rate * duration_sec)
        for i in range(total_frames):
            value = int(32767.0 * amplitude * math.sin(2 * math.pi * frequency * i / sample_rate))
            wf.writeframes(struct.pack("<h", value))


# ---------- fix for your translation example ----------
print("\n--- Fixed EN->FR translation (use text2text-generation) ---")
try:
    translator = pipeline(
        "text2text-generation",
        model="Helsinki-NLP/opus-mt-en-fr"
    )
    out = translator("Artificial Intelligence is amazing.", max_new_tokens=64)
    print(out)
except Exception as e:
    print("Translation example failed:", e)


# ---------- one example per available task ----------
# Note: Some tasks require extra deps, bigger models, or specific hardware.
TASK_EXAMPLES = {
    "any-to-any": {
        "model": "google/flan-t5-small",
        "input": "Translate to French: Artificial Intelligence is amazing."
    },
    "audio-classification": {
        "model": "superb/hubert-base-superb-ks",
        "input": str(audio_path)
    },
    "automatic-speech-recognition": {
        "model": "openai/whisper-tiny.en",
        "input": str(audio_path)
    },
    "depth-estimation": {
        "model": "Intel/dpt-large",
        "input": str(image_path)
    },
    "document-question-answering": {
        "model": "impira/layoutlm-document-qa",
        "input": {"image": str(image_path), "question": "What text is visible?"}
    },
    "feature-extraction": {
        "model": "sentence-transformers/all-MiniLM-L6-v2",
        "input": "Embeddings are useful for semantic search."
    },
    "fill-mask": {
        "model": "distilroberta-base",
        "input": "Paris is the <mask> of France."
    },
    "image-classification": {
        "model": "google/vit-base-patch16-224",
        "input": str(image_path)
    },
    "image-feature-extraction": {
        "model": "google/vit-base-patch16-224",
        "input": str(image_path)
    },
    "image-segmentation": {
        "model": "facebook/detr-resnet-50-panoptic",
        "input": str(image_path)
    },
    "image-text-to-text": {
        "model": "Qwen/Qwen2-VL-2B-Instruct",
        "input": str(image_path)
    },
    "keypoint-matching": {
        "model": "magic-leap-community/superpoint",
        "input": str(image_path)
    },
    "mask-generation": {
        "model": "facebook/sam-vit-base",
        "input": str(image_path)
    },
    "ner": {
        "model": "dslim/bert-base-NER",
        "input": "Sundar Pichai is the CEO of Google."
    },
    "object-detection": {
        "model": "facebook/detr-resnet-50",
        "input": str(image_path)
    },
    "sentiment-analysis": {
        "model": "distilbert/distilbert-base-uncased-finetuned-sst-2-english",
        "input": "I love learning NLP with Transformers."
    },
    "table-question-answering": {
        "model": "google/tapas-base-finetuned-wtq",
        "input": {
            "table": {
                "Country": ["France", "Germany"],
                "Capital": ["Paris", "Berlin"],
                "Population(M)": [67, 83]
            },
            "query": "What is the capital of Germany?"
        }
    },
    "text-classification": {
        "model": "distilbert-base-uncased-finetuned-sst-2-english",
        "input": "This workshop is very practical."
    },
    "text-generation": {
        "model": "gpt2",
        "input": "AI in healthcare can"
    },
    "text-to-audio": {
        "model": "facebook/musicgen-small",
        "input": "A calm piano melody with rain in the background"
    },
    "text-to-speech": {
        "model": "microsoft/speecht5_tts",
        "input": "Hello, this is a text to speech example."
    },
    "token-classification": {
        "model": "dslim/bert-base-NER",
        "input": "Microsoft was founded by Bill Gates."
    },
    "video-classification": {
        "model": "MCG-NJU/videomae-base-finetuned-kinetics",
        "input": str(video_path)
    },
    "zero-shot-audio-classification": {
        "model": "laion/clap-htsat-unfused",
        "input": {
            "audio": str(audio_path),
            "candidate_labels": ["speech", "music", "noise"]
        }
    },
    "zero-shot-classification": {
        "model": "facebook/bart-large-mnli",
        "input": {
            "sequences": "The movie was emotional and visually stunning.",
            "candidate_labels": ["entertainment", "politics", "sports"]
        }
    },
    "zero-shot-image-classification": {
        "model": "openai/clip-vit-base-patch32",
        "input": {
            "images": str(image_path),
            "candidate_labels": ["diagram", "animal", "person", "landscape"]
        }
    },
    "zero-shot-object-detection": {
        "model": "google/owlvit-base-patch32",
        "input": {
            "image": str(image_path),
            "candidate_labels": ["rectangle", "text", "person"]
        }
    }
}


def run_task_example(task_name: str, config: dict):
    model_name = config["model"]
    sample_input = config["input"]

    print(f"\n=== {task_name} ===")
    print("model:", model_name)

    try:
        pipe = pipeline(task_name, model=model_name)

        if isinstance(sample_input, dict):
            output = pipe(**sample_input)
        else:
            if task_name == "text-generation":
                output = pipe(sample_input, max_new_tokens=30, do_sample=False)
            else:
                output = pipe(sample_input)

        # Truncate long outputs for notebook readability.
        text_out = str(output)
        if len(text_out) > 700:
            text_out = text_out[:700] + " ...[truncated]"
        print(text_out)

    except Exception as err:
        print("Failed:", err)


for task, cfg in TASK_EXAMPLES.items():
    run_task_example(task, cfg)

print("\nDone. If some tasks failed, install missing deps/models and rerun only those tasks.")